### ISSUE TITLE
Update backend response to include preprint info

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/annorxiver-journal-recommender#55]
Currently on the frontend, I'm using a separate crossref query to lookup info about the inputted DOI to display to the user. But crossref can be "out of sync" with bio/medrxiv for newly published papers. To clean things up, we should just get all of our data from one source: bio/medrxiv.

The info I need is just the paper title, url, list of authors with given and family names, publisher, and year. Basically, everything that is shown right now in the "similar papers" section, I'd like to also show for the searched preprint.

**Comment by vincerubinetti** [comment]
I'd also like to suggest renaming `2d_coord` to `coordinates`, and `dim1` and `dim2` to just `x` and `y`. Let me know if you do want to make this change so I can make sure the frontend doesn't break.

**Comment by danich1** [comment]
> I'd also like to suggest renaming 2d_coord to coordinates, and dim1 and dim2 to just x and y. Let me know if you do want to make this change so I can make sure the frontend doesn't break.

I will make the name changes.

**Comment by vincerubinetti** [comment]
Great. To not break things, [these lines](https://github.com/greenelab/annorxiver-journal-recommender/blob/master/frontend/src/backend.js#L46-L49) can be replaced with/changed to: 
```javascript
const coordinates = neighbors.coordinates || {};
```
 and that's it!
